---
- name: Backports apt repo
  apt_repository:
    repo="deb http://ftp.debian.org/debian/ {{ ansible_lsb.codename }}-backports main non-free contrib"
    update_cache=yes
  when: ansible_distribution == 'Debian'
  sudo: yes

- name: Backported linux kernel
  apt:
    pkg={{ item }} state=present install_recommends=no
    default_release={{ ansible_lsb.codename }}-backports
  with_items:
    - linux-image-686-pae
    - linux-headers-686-pae
  sudo: yes
  register: kernel_upgrade

- name: New kernel version
  fail: msg="Please reboot the box!"
  when: kernel_upgrade|changed

- name: LXC apt package and options
  apt: pkg={{ item }} state=latest
  with_items:
    - lxc
    - bridge-utils
    - libvirt-bin
    - debootstrap
    - python3
    - python-libvirt
    - init-system-helpers
  sudo: yes

- name: CGroup mount point
  lineinfile:
    dest=/etc/fstab
    line='cgroup  /sys/fs/cgroup  cgroup  defaults  0   0'
    state=present
  sudo: yes

- name: Mount cgroup filesystem
  mount: name=/sys/fs/cgroup src=cgroup fstype=cgroup opts=defaults state=mounted
  when: (ansible_distribution is defined and
         ansible_distribution == 'Debian') and
        (ansible_distribution_release is defined and
         ansible_distribution_release == 'wheezy')
  sudo: yes
